// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdfVymD_x-yEAv0BZsz4Y9IDGkjpV9KNc',
    appId: '1:109387087972:web:54d0b0d7462fda7a401f71',
    messagingSenderId: '109387087972',
    projectId: 'whatsappnew-4fa1c',
    authDomain: 'whatsappnew-4fa1c.firebaseapp.com',
    storageBucket: 'whatsappnew-4fa1c.appspot.com',
    databaseURL: 'https://whatsappnew-4fa1c-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdfVymD_x-yEAv0BZsz4Y9IDGkjpV9KNc',
    appId: '1:109387087972:android:54d0b0d7462fda7a401f71',
    messagingSenderId: '109387087972',
    projectId: 'whatsappnew-4fa1c',
    storageBucket: 'whatsappnew-4fa1c.appspot.com',
    databaseURL: 'https://whatsappnew-4fa1c-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-IOS-API-KEY',
    appId: 'YOUR-IOS-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'whatsappnew-4fa1c',
    storageBucket: 'whatsappnew-4fa1c.appspot.com',
    iosBundleId: 'com.example.whatsappnew',
    databaseURL: 'https://whatsappnew-4fa1c-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR-MACOS-API-KEY',
    appId: 'YOUR-MACOS-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'whatsappnew-4fa1c',
    storageBucket: 'whatsappnew-4fa1c.appspot.com',
    iosBundleId: 'com.example.whatsappnew',
    databaseURL: 'https://whatsappnew-4fa1c-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR-WINDOWS-API-KEY',
    appId: 'YOUR-WINDOWS-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'whatsappnew-4fa1c',
    authDomain: 'whatsappnew-4fa1c.firebaseapp.com',
    storageBucket: 'whatsappnew-4fa1c.appspot.com',
    databaseURL: 'https://whatsappnew-4fa1c-default-rtdb.firebaseio.com',
  );


}
 